# This is the compose file for the local dev env.
version: '2'
services:
  "asl-db":
    image: "mysql:5.7"
    # volumes:
    #  - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: asl
      MYSQL_USER: asl
      MYSQL_PASSWORD: asl
    ports:
     - "33006:3306"
  "asl-server":
    env_file: common.env
    build: .
    ports:
     - "3275:3275"
    volumes:
     - ./src:/var/www/app/current/src
     - ./bin:/var/www/app/current/bin
     - ./migrations:/var/www/app/current/migrations
    depends_on:
     - asl-db
    environment:
      PORT: 3275
      ASL_DB_HOST: asl-db
      ASL_DB_USER: asl
      ASL_DB_PASSWORD: asl
      ASL_DB_NAME: asl
# volumes:
#   db_data:

